### ISSUE TITLE
CRLF

### ISSUE THREAD

**Issue by acurrieclark** [danxexe/sms-counter#9]
Am I not correct in saying that a return should be counted as 2 characters? I have a fix for this if you like, but I just wanted to check this hadn't been deliberately omitted for any reason.

**Comment by danxexe** [comment]
Hi @acurrieclark, it is counted as 2 characters if the text contains both CR and LF:

```js
SmsCounter.count("\r\n").length // 2
```

But only one if there's just a LF:

```js
SmsCounter.count("\n").length // 1
```

It depends on what your text input element actually inserts when you hit return. It may vary between browsers and OSes.

**Comment by acpmasquerade** [comment]
@danxexe +1. Why not close this issue ?

**Comment by acurrieclark** [comment]
What I am really suggesting is that an SMS will always (to my understanding) use a /r/n and therefore 2 characters. In that case, regardless of whether or not the browser is using /n or /r/n, it should always be counted as 2 characters.



__
Alex Currie-Clark
Tel: 07825 346673

**Comment by danxexe** [comment]
I didn't find any specification stating that SMS messages must use `\r\n`, and in practice it seems several systems do send messages with just `\n` and most clients seem to work fine with that. I don't see any reason to limit the user and display an incorrect value if the user wishes to use just a `\n`.

You could always use something like `message.replace(/\r?\n/g, "\r\n")` if you wish to ensure you are always sending both characters.
